# Generated by Django 6.1.1 on 2026-09-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_part', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'muscle_groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.ForeignKey(db_column='muscle_group_id', on_delete=django.db.models.deletion.CASCADE, to='someappi.musclegroup')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('started_ad', models.CharField(max_length=255)),
                ('duration_min', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='someappi.user')),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('exercises', models.ForeignKey(db_column='exercises_id', on_delete=django.db.models.deletion.CASCADE, to='someappi.exercise')),
                ('workout', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, to='someappi.workout')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
    ]
